account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('account:password_change_done')
    ), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('account:password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('account:password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

main_system/urls.py
from django.urls import path
from . import views

app_name = 'main_system'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('dashboard/', views.offer_list, name='offer_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:provider>/', views.offer_detail, name='offer_detail'),
    path('remove_offer/<int:offer_id>/', views.remove_offer, name='remove_offer'),
    path('take_offer/<int:offer_id>', views.take_offer, name='take_offer'),
    path('user_panel/', views.user_panel, name='user_panel'),
    path('estimate_costs/', views.estimate_costs, name='estimate_costs'),
]

special_events_organizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('main_system.urls', namespace='main_system'))
]

main_system/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Location(models.Model):
    district = models.CharField(max_length=100)
    town = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    local_number = models.CharField(max_length=10)

    def __str__(self):
        return self.street + " " + self.local_number + " " + self.town


class Contact(models.Model):
    phone_number = models.CharField(max_length=20)
    website = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)

    def __str__(self):
        string_website = self.website
        string_email = self.email
        if string_website is None:
            string_website = ""
        if string_email is None:
            string_email = ""

        return self.phone_number + " " + string_website + " " + string_email


class Catering(models.Model):
    location = models.OneToOneField(Location, on_delete=models.CASCADE)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    with_local_only = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, unique_for_date='added')

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('main_system:offer_detail',
                       args=[self.added.year, self.added.month,
                       self.added.day, self.slug])

    def __str__(self):
        return self.name


class Local(models.Model):
    location = models.OneToOneField(Location, on_delete=models.CASCADE)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE)
    catering = models.OneToOneField(Catering, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, unique_for_date='added')

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('main_system:offer_detail', args=[self.added.year, self.added.month,
                                                         self.added.day, self.slug])

    def __str__(self):
        return self.name


class OtherProvider(models.Model):
    location = models.OneToOneField(Location, on_delete=models.CASCADE)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, unique_for_date='added')

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('main_system:offer_detail', args=[self.added.year, self.added.month,
                                                         self.added.day, self.slug])

    def __str__(self):
        return self.name


class Offer(models.Model):
    local = models.ForeignKey(Local, on_delete=models.CASCADE, blank=True, null=True)
    catering = models.ForeignKey(Catering, on_delete=models.CASCADE, blank=True, null=True)
    other_provider = models.ForeignKey(OtherProvider, on_delete=models.CASCADE, blank=True, null=True)
    max_people = models.IntegerField(blank=True, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=100)
    offer_description = models.TextField(blank=True, null=True)
    added = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=100, unique_for_date='added')

    def get_absolute_url(self):
        return reverse('main_system:take_room_offer', args=[self.added.year, self.added.month,
                                                            self.added.day, self.slug])

    def __str__(self):
        if self.local is not None:
            provider_name = self.local.name
        elif self.catering is not None:
            provider_name = self.catering.name
        else:
            provider_name = self.other_provider.name
        return provider_name + " - " + str(self.name)


class Comment(models.Model):
    catering = models.ForeignKey(Catering, on_delete=models.CASCADE, null=True, blank=True, related_name='comments')
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True, related_name='comments')
    other_provider = models.ForeignKey(OtherProvider, on_delete=models.CASCADE, null=True, blank=True,
                                       related_name='comments')
    name = models.CharField(max_length=50)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Komentarz dodany przez {self.name} dla oferty .'

main_system/forms.py
from django import forms
from .models import Comment


class FilterOffersForm(forms.Form):

    EVENT_CHOICES = (
        ('BAL', 'BAL'),
        ('CHRZEST', 'CHRZEST'),
        ('JUBILEUSZ', 'JUBILEUSZ'),
        ('KOMUNIA ŚWIĘTA', 'KOMUNIA ŚWIĘTA'),
        ('POGRZEB', 'POGRZEB'),
        ('PRZYJĘCIE', 'PRZYJĘCIE'),
        ('WESELE', 'WESELE'),
    )

    filtered_event = forms.ChoiceField(choices=EVENT_CHOICES, label='Uroczystość')
    filtered_location = forms.CharField(max_length=50, label='Lokalizacja')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        labels = {'body': ''}


class EstimationForm(forms.Form):
    people_amount = forms.IntegerField(max_value=1000, label='')

main_system/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Local, Catering, Offer, OtherProvider
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import FilterOffersForm, CommentForm, EstimationForm
from account.models import Profile
from django.contrib import messages


def main_page(request):
    return render(request, 'main_page/main_page.html')


def offer_list(request):
    if request.method == 'GET':
        form = FilterOffersForm()

        locals = Local.objects.all()
        caterings = Catering.objects.all()
        other_providers= OtherProvider.objects.all()
        providers = list()

        for local in locals:
            providers.append(local)
        for catering in caterings:
            providers.append(catering)
        for other_provider in other_providers:
            providers.append(other_provider)

        providers.sort(key=lambda r: r.added, reverse=True)
        paginator = Paginator(providers, 3)
        page = request.GET.get('page')
        try:
            providers = paginator.page(page)
        except PageNotAnInteger:
            providers = paginator.page(1)
        except EmptyPage:
            providers = paginator.page(paginator.num_pages)

        return render(request, 'main_page/offer_list.html', {'page': page, 'providers': providers, 'form': form})

    else:
        form = FilterOffersForm(request.POST)
        if form.is_valid():
            providers = list()
            filtered_location = form.cleaned_data['filtered_location']
            filtered_event = form.cleaned_data['filtered_event']
            tag = get_object_or_404(Tag, name=filtered_event)

            locals = Local.objects.filter(location__district=filtered_location, tags__name__in=[tag])
            caterings = Catering.objects.filter(location__district=filtered_location, tags__name__in=[tag])
            other_providers = OtherProvider.objects.filter(location__district=filtered_location, tags__name__in=[tag])

            for local in locals:
                providers.append(local)
            for catering in caterings:
                providers.append(catering)
            for other_offer in other_providers:
                providers.append(other_offer)

            if len(providers) == 0:
                town_providers = list()
                locals = Local.objects.filter(location__town=filtered_location, tags__name__in=[tag])
                caterings = Catering.objects.filter(location__town=filtered_location, tags__name__in=[tag])
                other_providers = OtherProvider.objects.filter(location__town=filtered_location, tags__name__in=[tag])
                for local in locals:
                    town_providers.append(local)
                for catering in caterings:
                    town_providers.append(catering)
                for other_provider in other_providers:
                    town_providers.append(other_provider)

                if len(town_providers):
                    district = town_providers[0].location.district
                    locals = Local.objects.filter(location__district=district, tags__name__in=[tag])
                    caterings = Catering.objects.filter(location__district=district, tags__name__in=[tag])
                    other_offers = OtherProvider.objects.filter(location__district=district, tags__name__in=[tag])
                    for local in locals:
                        providers.append(local)
                    for catering in caterings:
                        providers.append(catering)
                    for other_offer in other_offers:
                        providers.append(other_offer)

            providers.sort(key=lambda r: r.added, reverse=True)
            paginator = Paginator(providers, 3)
            page = request.GET.get('page')
            try:
                providers = paginator.page(page)
            except PageNotAnInteger:
                providers = paginator.page(1)
            except EmptyPage:
                providers = paginator.page(paginator.num_pages)

            return render(request, 'main_page/offer_list.html', {'page': page, 'providers': providers,
                                                                 'form': form})


@login_required
def offer_detail(request, year, month, day, provider):
    new_comment = None

    catering = Catering.objects.filter(slug=provider, added__year=year, added__month=month, added__day=day)
    if len(catering) == 0:
        local = Local.objects.filter(slug=provider, added__year=year, added__month=month, added__day=day)
        if len(local) == 0:
            other_provider = OtherProvider.objects.filter(slug=provider, added__year=year,
                                                          added__month=month, added__day=day)
            other_provider = other_provider[0]
            offers = Offer.objects.filter(other_provider=other_provider.id)
            comments = other_provider.comments.filter(active=True)
            if request.method == 'POST':
                comment_form = CommentForm(data=request.POST)
                if comment_form.is_valid():
                    new_comment = comment_form.save(commit=False)
                    new_comment.name = request.user.username
                    new_comment.other_provider = other_provider
                    new_comment.save()
            else:
                comment_form = CommentForm()
            return render(request, 'main_page/other_provider_detail.html',
                          {'other_provider': other_provider, 'comments': comments,
                           'comment_form': comment_form, 'new_comment': new_comment,
                           'offers': offers})
        else:
            local = local[0]
            offers = Offer.objects.filter(local=local.id)
            comments = local.comments.filter(active=True)
            if request.method == 'POST':
                comment_form = CommentForm(data=request.POST)
                if comment_form.is_valid():
                    new_comment = comment_form.save(commit=False)
                    new_comment.name = request.user.username
                    new_comment.local = local
                    new_comment.save()
            else:
                comment_form = CommentForm()
            return render(request, 'main_page/local_detail.html',
                          {'local': local, 'offers': offers, 'comments': comments,
                           'comment_form': comment_form, 'new_comment': new_comment})

    catering = catering[0]
    offers = Offer.objects.filter(catering=catering.id)
    comments = catering.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.name = request.user.username
            new_comment.catering = catering
            new_comment.save()
            messages.success(request, 'Twój komentarz został dodany')
    else:
        comment_form = CommentForm()
    return render(request, 'main_page/catering_detail.html', {'catering': catering, 'comments': comments,
                                                              'offers': offers, 'comment_form': comment_form,
                                                              'new_comment': new_comment})


@login_required
def take_offer(request, offer_id):
    offer = Offer.objects.filter(id=offer_id)
    offer = offer[0]
    profile = Profile.objects.get(user=request.user)
    profile.offers.add(offer)

    return render(request, 'user_panel/offer_added.html', {'offer': offer})


@login_required
def remove_offer(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)

    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        profile.offers.remove(offer)
        messages.success(request, 'Wybrana oferta została usunięta.')
        return redirect('main_system:user_panel')

    return render(request, 'user_panel/confirm_removing_offer.html', {'offer': offer})


@login_required
def user_panel(request):
    profile = Profile.objects.get(user=request.user)
    offers = profile.offers.all()

    return render(request, 'user_panel/user_panel.html', {'offers': offers})


@login_required
def estimate_costs(request):
    profile = Profile.objects.get(user=request.user)
    offers = profile.offers.all()
    final_cost = 0

    if request.method == 'POST':
        form = EstimationForm(data=request.POST)
        if form.is_valid():
            people_amount = form.cleaned_data['people_amount']

            for offer in offers:
                if offer.catering is not None:
                    final_cost += offer.cost * people_amount
                else:
                    final_cost += offer.cost

            return render(request, 'user_panel/costs_counting.html', {'form': form, 'offers': offers, 'final_cost': final_cost})
    else:
        form = EstimationForm()
        return render(request, 'user_panel/costs_counting.html', {'offers': offers, 'form': form, 'final_cost': final_cost})

main_system/templates/main_page/catering_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block page_header %}
    <h2>{{ catering.name }}</h2>
    <h5>{{ catering.location.street }} {{ catering.location.local_number}} {{ catering.location.town }}</h5>

    <p>
        {% if catering.with_local_only %}
            Ten katering jest ofertą jednego z lokali.
        {% endif %}
    </p>
{% endblock %}


{% block content %}
    <div class="card mb-3">
        <h4 class="card-header">
            OFERTY
        </h4>
        <div class="card-body">
            {% for offer in offers %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ offer.name }}<br>
                    </h5>
                    <p>
                        {% if offer.offer_description %}
                            {{ offer.offer_description }}<br>
                        {% endif %}
                        Cena za jedną osobę: {{ offer.cost }} zł<br>
                        <a href="{% url 'main_system:take_offer' offer.id %}">Dodaj do moich ofert</a>
                    </p>
                </div>
        </div>
    {% endfor %}
        </div>
    </div>

    <div class="card mb-3">
        <h4 class="card-header">
            KONTAKT
        </h4>
        <div class="card-body">
            <div class="card-text">
                <table class="table table-sm table-bordered">
                    <tr><td>Numer telefonu</td><td>{{ catering.contact.phone_number }}</td></tr>
                    {% if catering.contact.email %}
                        <tr><td>E-mail</td><td>{{ catering.contact.email }}</td></tr>
                    {% endif %}
                    {% if catering.contact.website %}
                        <tr><td>Internet</td><td>{{ catering.contact.website }}</td></tr>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>

    <div class="card mb-3">
        <h4 class="card-header">
            {% with comments.count as total_comments %}
                KOMENTARZE ({{ total_comments }})
            {% endwith %}
        </h4>
        <div class="card-body">
        {% for comment in comments %}
            <div class="card mb-3">
                    <div class="card-body">
                        <div class="card-title">
                            <small>Użytkownik {{ comment.name }} skomentował {{ comment.created }}:</small>
                        </div>
                        <div class="card-text">
                            {{ comment.body|linebreaks }}
                        </div>
                    </div>
                </div>

            {% empty %}
                <p>Nie ma jeszcze żadnych komentarzy.</p>
            {% endfor %}


            <h4>Dodaj nowy komentarz:</h4>
            <form action="." method="post">
                {% bootstrap_form comment_form %}
                {% csrf_token %}
                {% buttons %}
                    <button name="submit" class="btn btn-primary">Dodaj komentarz</button>
                {% endbuttons %}
            </form>
        </div>
    </div>


    {% endblock %}

main_system/templates/main_page/local_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>{{ local.name }}</h2>
    <h5>{{ local.location.street }} {{ local.location.local_number}} {{ local.location.town }}</h5>

    <p>
        {% if local.catering is not None %}
            W tym lokalu dostępny jest tylko i wyłącznie katering {{ local.catering.name }}.
        {% endif %}
    </p>
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <h4 class="card-header">
            SALE DOSTĘPNE W LOKALU
        </h4>
        <div class="card-body">
            {% for offer in offers %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ offer.name }}<br>
                    </h5>
                    <p>
                        {% if offer.offer_description %}
                            {{ offer.offer_description }}<br>
                        {% endif %}
                        Maksymalna pojemność sali: {{ offer.max_people }} osób<br>
                        Cena: {{ offer.cost }} zł<br>
                        <a href="{% url 'main_system:take_offer' offer.id %}">Dodaj do moich ofert</a>
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="card mb-3">
        <h4 class="card-header">
            KONTAKT
        </h4>
        <div class="card-body">
            <div class="card-text">
                <table class="table table-sm table-bordered">
                    <tr><td>Numer telefonu</td><td>{{ local.contact.phone_number }}</td></tr>
                    {% if local.contact.email %}
                        <tr><td>E-mail</td><td>{{ local.contact.email }}</td></tr>
                    {% endif %}
                    {% if local.contact.website %}
                        <tr><td>Internet</td><td>{{ local.contact.website }}</td></tr>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>


    <div class="card mb-3">
        <h4 class="card-header">
            {% with comments.count as total_comments %}
                KOMENTARZE ({{ total_comments }})
            {% endwith %}
        </h4>
        <div class="card-body">
        {% for comment in comments %}
            <div class="card mb-3">
                    <div class="card-body">
                        <div class="card-title">
                            <small>Użytkownik {{ comment.name }} skomentował {{ comment.created }}:</small>
                        </div>
                        <div class="card-text">
                            {{ comment.body|linebreaks }}
                        </div>
                    </div>
                </div>

            {% empty %}
                <p>Nie ma jeszcze żadnych komentarzy.</p>
            {% endfor %}


            <h4>Dodaj nowy komentarz:</h4>
            <form action="." method="post">
                {% bootstrap_form comment_form %}
                {% csrf_token %}
                {% buttons %}
                    <button name="submit" class="btn btn-primary">Dodaj komentarz</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

main_system/templates/main_page/main_page.html
{% extends "base.html" %}

{% block page_header%}
    <div class="jumbotron ">
        <h3>Zorganizuj uroczystość nie wychodząc z domu!</h3>

        <p>
            Określ rodzaj uroczystości, którą chcesz zorganizować, znajdź najlepszy lokal w okolicy i wybierz
            najatrakcyjniejszą obsługę.
            Zarejestruj się, aby mieć dostęp do szczegółów, kompletować oferty,
            szacować łączny koszt uroczystości lub dodawać komentarze
            do wybranych ofert.
        </p>

        <a class="btn btn-lg btn-primary" href="{% url 'main_system:offer_list' %}"
           role="button">Przejdź do wyszukiwania &raquo;</a>

        <a class="btn btn-lg btn-primary" href="{% url 'account:register' %}"
           role="button">Załóż konto &raquo;</a>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <p>
            Chcesz zamieścić ofertę swojej działalności w serwisie? Skontaktuj się z nami:<br>
            e-mail: admin@serwis.pl<br>
            numer telefonu: 222444444
        </p>
    </div>
{% endblock %}

main_system/templates/main_page/offer_list.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}

        <h5>Wybierz organizowaną uroczystość, a następnie
        podaj miasto na terenie którego chcesz aby się odbyła (jeśli mieszkasz w mniejszej miejscowości
            zalecane jest, abyś podał nazwę powiatu):</h5>
    <p>
        <form action="." method="post" class="form">
        {% bootstrap_form form %}
        {% csrf_token %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Wyszukaj</button>
        {% endbuttons %}
    </form>
    </p>
{% endblock %}

{% block content %}
    {% if request.method == 'GET' %}
        <h3>Ostatnio dodani dostawcy:</h3>
    {% else %}
        <h3>Wyszukani dostawcy:</h3>
    {% endif %}

    {% for provider in providers %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ provider }}
                <small><a href="{{ provider.get_absolute_url }}">Oferty</a> </small>
            </h4>
            <div class="card-body">
                <div class="card-text">
                    <table class="table table-sm table-bordered">
                        <tr><td>Adres</td><td>{{ provider.location }}</td></tr>
                        <tr><td>Numer telefonu</td><td>{{ provider.contact.phone_number }}</td></tr>
                        {% if provider.contact.email %}
                        <tr><td>E-mail</td><td>{{ provider.contact.email }}</td></tr>
                        {% endif %}
                        {% if provider.contact.website %}
                        <tr><td>Internet</td><td>{{ provider.contact.website }}</td></tr>
                        {% endif %}
                    </table>

                </div>
                <div class="card-text text-right text-small">
                    Dodano: {{ provider.added }}
                </div>
            </div>
        </div>
    {% endfor %}
    {% include "pagination.html" with page=providers %}
{% endblock %}

main_system/templates/main_page/other_provider_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>{{ other_provider.name }}</h2>
    <h5>{{ other_provider.location.street }} {{ other_provider.location.local_number}}
        {{ other_provider.location.town }}</h5>
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <h4 class="card-header">
            OFERTY
        </h4>
        <div class="card-body">
            {% for offer in offers %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ offer.name }}<br>
                    </h5>
                    <p>
                        {% if offer.offer_description %}
                            {{ offer.offer_description }}<br>
                        {% endif %}
                        Cena: {{ offer.cost }} zł<br>
                        <a href="{% url 'main_system:take_offer' offer.id %}">Dodaj do moich ofert</a>
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="card mb-3">
        <h4 class="card-header">
            KONTAKT
        </h4>
        <div class="card-body">
            <div class="card-text">
                <table class="table table-sm table-bordered">
                    <tr><td>Numer telefonu</td><td>{{ other_provider.contact.phone_number }}</td></tr>
                    {% if other_provider.contact.email %}
                        <tr><td>E-mail</td><td>{{ other_provider.contact.email }}</td></tr>
                    {% endif %}
                    {% if other_provider.contact.website %}
                        <tr><td>Internet</td><td>{{ other_provider.contact.website }}</td></tr>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>


    <div class="card mb-3">
        <h4 class="card-header">
            {% with comments.count as total_comments %}
                KOMENTARZE ({{ total_comments }})
            {% endwith %}
        </h4>
        <div class="card-body">
        {% for comment in comments %}
            <div class="card mb-3">
                    <div class="card-body">
                        <div class="card-title">
                            <small>Użytkownik {{ comment.name }} skomentował {{ comment.created }}:</small>
                        </div>
                        <div class="card-text">
                            {{ comment.body|linebreaks }}
                        </div>
                    </div>
                </div>

            {% empty %}
                <p>Nie ma jeszcze żadnych komentarzy.</p>
            {% endfor %}


            <h4>Dodaj nowy komentarz:</h4>
            <form action="." method="post">
                {% bootstrap_form comment_form %}
                {% csrf_token %}
                {% buttons %}
                    <button name="submit" class="btn btn-primary">Dodaj komentarz</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}