account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('account:password_change_done')
    ), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('account:password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('account:password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

main_system/urls.py
from django.urls import path
from . import views

app_name = 'main_system'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('dashboard/', views.offer_list, name='offer_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:provider>/', views.offer_detail, name='offer_detail'),
    path('remove_offer/<int:offer_id>/', views.remove_offer, name='remove_offer'),
    path('take_offer/<int:offer_id>', views.take_offer, name='take_offer'),
    path('user_panel/', views.user_panel, name='user_panel'),
    path('estimate_costs/', views.estimate_costs, name='estimate_costs'),
]

special_events_organizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('main_system.urls', namespace='main_system'))
]

main_system/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Location(models.Model):
    district = models.CharField(max_length=100)
    town = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    local_number = models.CharField(max_length=10)

    def __str__(self):
        return self.street + " " + self.local_number + " " + self.town


class Contact(models.Model):
    phone_number = models.CharField(max_length=20)
    website = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)

    def __str__(self):
        string_website = self.website
        string_email = self.email
        if string_website is None:
            string_website = ""
        if string_email is None:
            string_email = ""

        return self.phone_number + " " + string_website + " " + string_email


class Catering(models.Model):
    location = models.OneToOneField(Location, on_delete=models.CASCADE)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    with_local_only = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, unique_for_date='added')

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('main_system:offer_detail',
                       args=[self.added.year, self.added.month,
                       self.added.day, self.slug])

    def __str__(self):
        return self.name


class Local(models.Model):
    location = models.OneToOneField(Location, on_delete=models.CASCADE)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE)
    catering = models.OneToOneField(Catering, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, unique_for_date='added')

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('main_system:offer_detail', args=[self.added.year, self.added.month,
                                                         self.added.day, self.slug])

    def __str__(self):
        return self.name


class OtherProvider(models.Model):
    location = models.OneToOneField(Location, on_delete=models.CASCADE)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, unique_for_date='added')

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('main_system:offer_detail', args=[self.added.year, self.added.month,
                                                         self.added.day, self.slug])

    def __str__(self):
        return self.name


class Offer(models.Model):
    local = models.ForeignKey(Local, on_delete=models.CASCADE, blank=True, null=True)
    catering = models.ForeignKey(Catering, on_delete=models.CASCADE, blank=True, null=True)
    other_provider = models.ForeignKey(OtherProvider, on_delete=models.CASCADE, blank=True, null=True)
    max_people = models.IntegerField(blank=True, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    name = models.CharField(max_length=100)
    offer_description = models.TextField(blank=True, null=True)
    added = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=100, unique_for_date='added')

    def get_absolute_url(self):
        return reverse('main_system:take_room_offer', args=[self.added.year, self.added.month,
                                                            self.added.day, self.slug])

    def __str__(self):
        if self.local is not None:
            provider_name = self.local.name
        elif self.catering is not None:
            provider_name = self.catering.name
        else:
            provider_name = self.other_provider.name
        return provider_name + " - " + str(self.name)


class Comment(models.Model):
    catering = models.ForeignKey(Catering, on_delete=models.CASCADE, null=True, blank=True, related_name='comments')
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True, related_name='comments')
    other_provider = models.ForeignKey(OtherProvider, on_delete=models.CASCADE, null=True, blank=True,
                                       related_name='comments')
    name = models.CharField(max_length=50)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Komentarz dodany przez {self.name} dla oferty .'

main_system/forms.py
from django import forms
from .models import Comment


class FilterOffersForm(forms.Form):

    EVENT_CHOICES = (
        ('BAL', 'BAL'),
        ('CHRZEST', 'CHRZEST'),
        ('JUBILEUSZ', 'JUBILEUSZ'),
        ('KOMUNIA ŚWIĘTA', 'KOMUNIA ŚWIĘTA'),
        ('POGRZEB', 'POGRZEB'),
        ('PRZYJĘCIE', 'PRZYJĘCIE'),
        ('WESELE', 'WESELE'),
    )

    filtered_event = forms.ChoiceField(choices=EVENT_CHOICES, label='Uroczystość')
    filtered_location = forms.CharField(max_length=50, label='Lokalizacja')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        labels = {'body': ''}


class EstimationForm(forms.Form):
    people_amount = forms.IntegerField(max_value=1000, label='')

main_system/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Local, Catering, Offer, OtherProvider
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import FilterOffersForm, CommentForm, EstimationForm
from account.models import Profile
from django.contrib import messages


def main_page(request):
    return render(request, 'main_page/main_page.html')


def offer_list(request):
    if request.method == 'GET':
        form = FilterOffersForm()

        locals = Local.objects.all()
        caterings = Catering.objects.all()
        other_providers= OtherProvider.objects.all()
        providers = list()

        for local in locals:
            providers.append(local)
        for catering in caterings:
            providers.append(catering)
        for other_provider in other_providers:
            providers.append(other_provider)

        providers.sort(key=lambda r: r.added, reverse=True)
        paginator = Paginator(providers, 3)
        page = request.GET.get('page')
        try:
            providers = paginator.page(page)
        except PageNotAnInteger:
            providers = paginator.page(1)
        except EmptyPage:
            providers = paginator.page(paginator.num_pages)

        return render(request, 'main_page/offer_list.html', {'page': page, 'providers': providers, 'form': form})

    else:
        form = FilterOffersForm(request.POST)
        if form.is_valid():
            providers = list()
            filtered_location = form.cleaned_data['filtered_location']
            filtered_event = form.cleaned_data['filtered_event']
            tag = get_object_or_404(Tag, name=filtered_event)

            locals = Local.objects.filter(location__district=filtered_location, tags__name__in=[tag])
            caterings = Catering.objects.filter(location__district=filtered_location, tags__name__in=[tag])
            other_providers = OtherProvider.objects.filter(location__district=filtered_location, tags__name__in=[tag])

            for local in locals:
                providers.append(local)
            for catering in caterings:
                providers.append(catering)
            for other_offer in other_providers:
                providers.append(other_offer)

            if len(providers) == 0:
                town_providers = list()
                locals = Local.objects.filter(location__town=filtered_location, tags__name__in=[tag])
                caterings = Catering.objects.filter(location__town=filtered_location, tags__name__in=[tag])
                other_providers = OtherProvider.objects.filter(location__town=filtered_location, tags__name__in=[tag])
                for local in locals:
                    town_providers.append(local)
                for catering in caterings:
                    town_providers.append(catering)
                for other_provider in other_providers:
                    town_providers.append(other_provider)

                if len(town_providers):
                    district = town_providers[0].location.district
                    locals = Local.objects.filter(location__district=district, tags__name__in=[tag])
                    caterings = Catering.objects.filter(location__district=district, tags__name__in=[tag])
                    other_offers = OtherProvider.objects.filter(location__district=district, tags__name__in=[tag])
                    for local in locals:
                        providers.append(local)
                    for catering in caterings:
                        providers.append(catering)
                    for other_offer in other_offers:
                        providers.append(other_offer)

            providers.sort(key=lambda r: r.added, reverse=True)
            paginator = Paginator(providers, 3)
            page = request.GET.get('page')
            try:
                providers = paginator.page(page)
            except PageNotAnInteger:
                providers = paginator.page(1)
            except EmptyPage:
                providers = paginator.page(paginator.num_pages)

            return render(request, 'main_page/offer_list.html', {'page': page, 'providers': providers,
                                                                 'form': form})


@login_required
def offer_detail(request, year, month, day, provider):
    new_comment = None

    catering = Catering.objects.filter(slug=provider, added__year=year, added__month=month, added__day=day)
    if len(catering) == 0:
        local = Local.objects.filter(slug=provider, added__year=year, added__month=month, added__day=day)
        if len(local) == 0:
            other_provider = OtherProvider.objects.filter(slug=provider, added__year=year,
                                                          added__month=month, added__day=day)
            other_provider = other_provider[0]
            offers = Offer.objects.filter(other_provider=other_provider.id)
            comments = other_provider.comments.filter(active=True)
            if request.method == 'POST':
                comment_form = CommentForm(data=request.POST)
                if comment_form.is_valid():
                    new_comment = comment_form.save(commit=False)
                    new_comment.name = request.user.username
                    new_comment.other_provider = other_provider
                    new_comment.save()
            else:
                comment_form = CommentForm()
            return render(request, 'main_page/other_provider_detail.html',
                          {'other_provider': other_provider, 'comments': comments,
                           'comment_form': comment_form, 'new_comment': new_comment,
                           'offers': offers})
        else:
            local = local[0]
            offers = Offer.objects.filter(local=local.id)
            comments = local.comments.filter(active=True)
            if request.method == 'POST':
                comment_form = CommentForm(data=request.POST)
                if comment_form.is_valid():
                    new_comment = comment_form.save(commit=False)
                    new_comment.name = request.user.username
                    new_comment.local = local
                    new_comment.save()
            else:
                comment_form = CommentForm()
            return render(request, 'main_page/local_detail.html',
                          {'local': local, 'offers': offers, 'comments': comments,
                           'comment_form': comment_form, 'new_comment': new_comment})

    catering = catering[0]
    offers = Offer.objects.filter(catering=catering.id)
    comments = catering.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.name = request.user.username
            new_comment.catering = catering
            new_comment.save()
            messages.success(request, 'Twój komentarz został dodany')
    else:
        comment_form = CommentForm()
    return render(request, 'main_page/catering_detail.html', {'catering': catering, 'comments': comments,
                                                              'offers': offers, 'comment_form': comment_form,
                                                              'new_comment': new_comment})


@login_required
def take_offer(request, offer_id):
    offer = Offer.objects.filter(id=offer_id)
    offer = offer[0]
    profile = Profile.objects.get(user=request.user)
    profile.offers.add(offer)

    return render(request, 'user_panel/offer_added.html', {'offer': offer})


@login_required
def remove_offer(request, offer_id):
    offer = get_object_or_404(Offer, id=offer_id)

    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        profile.offers.remove(offer)
        messages.success(request, 'Wybrana oferta została usunięta.')
        return redirect('main_system:user_panel')

    return render(request, 'user_panel/confirm_removing_offer.html', {'offer': offer})


@login_required
def user_panel(request):
    profile = Profile.objects.get(user=request.user)
    offers = profile.offers.all()

    return render(request, 'user_panel/user_panel.html', {'offers': offers})


@login_required
def estimate_costs(request):
    profile = Profile.objects.get(user=request.user)
    offers = profile.offers.all()
    final_cost = 0

    if request.method == 'POST':
        form = EstimationForm(data=request.POST)
        if form.is_valid():
            people_amount = form.cleaned_data['people_amount']

            for offer in offers:
                if offer.catering is not None:
                    final_cost += offer.cost * people_amount
                else:
                    final_cost += offer.cost

            return render(request, 'user_panel/costs_counting.html', {'form': form, 'offers': offers, 'final_cost': final_cost})
    else:
        form = EstimationForm()
        return render(request, 'user_panel/costs_counting.html', {'offers': offers, 'form': form, 'final_cost': final_cost})

main_system/templates/user_panel/confirm_removing_offer.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h6>Czy na pewno chcesz usunać wybraną ofertę?</h6>
{% endblock %}

{% block content %}
<form action="{% url 'main_system:remove_offer' offer.id %}"
      method="post" xmlns="http://www.w3.org/1999/html">
        {% csrf_token %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Tak</button>
        {% endbuttons %}
        <p><a href="{% url 'main_system:user_panel' %}">Anuluj</a></p>
    </form>
{% endblock %}

main_system/templates/user_panel/costs_counting.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Podsumowanie kosztów</h3>
    <h6>Poniższa tabela przedstawia koszt każdej z wybranych przez Ciebie ofert.
        Koszty kateringów i cukierni to koszty posiłków dla jednej osoby.
        Wypełnij poniższy formularz abyśmy mogli obliczyć całkowity
        koszt Twojej uroczystości.</h6>
{% endblock %}

{% block content %}
    <table class="table table-striped">
        {% for offer in offers %}
            <tr>
                <td>{{ forloop.counter }}.</td><td>{{ offer }}</td>
                {% if offer.catering %}
                   <td> {{ offer.cost }} zł / osobę</td>
                {% else %}
                    <td> {{ offer.cost }} zł</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
    {% if final_cost == 0 %}
    <h6>Podaj przewidywaną liczbę osób biorących udział w uroczystości:</h6>
        <form action="." method="post">
            {% bootstrap_form form %}
            {% csrf_token %}
            {% buttons %}
                <button name="submit" class="btn btn-primary">Oblicz łączny koszt</button>
            {% endbuttons %}
        </form>
    {% else %}
    <h6>Koszt wybranych przez Ciebie ofert to {{ final_cost }} zł.</h6>
    {% endif %}
{% endblock %}

main_system/templates/user_panel/offer_added.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h5>Wybrana oferta została dodana do Twoich ofert.
        Obejrzyj je wszystkie lub wróć do wyszukiwania:</h5>
{% endblock %}

{% block content %}
    <p>
        <a class="btn btn-primary" href="#" onclick='history.go(-2)'>Cofnij do wyszukiwania</a>
        <a class="btn btn-primary" href="{% url 'main_system:user_panel' %}">Moje oferty</a>
    </p>
{% endblock %}

main_system/templates/user_panel/user_panel.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Twoje oferty</h3>
{% endblock %}

{% block content %}
    {% for offer in offers %}
        <div class="card mb-3">
            <div class="card-body">
                {% if offer.local %}
                    <div class="card-title">
                        <h4>{{ offer }}</h4>
                    </div>
                    <div class="card-subtitle">
                        <h6 class="text-muted">{{ offer.local.location }}</h6>
                    </div>
                    {% if offer.offer_description %}
                        {{ offer.offer_description }}<br>
                    {% endif %}
                    Numer telefonu: {{ offer.local.contact.phone_number }}<br>
                    Koszt: {{ offer.cost }} zł.<br>
                    <a href="{% url 'main_system:remove_offer' offer.id %}">Usuń ofertę</a>
                {% elif offer.catering %}
                    <div class="card-title">
                        <h4>{{ offer }}</h4>
                    </div>
                    <div class="card-subtitle">
                        <h6 class="text-muted">{{ offer.catering.location }}</h6>
                    </div>
                    {% if offer.offer_description %}
                        {{ offer.offer_description }}<br>
                    {% endif %}
                    Numer telefonu: {{ offer.catering.contact.phone_number }}<br>
                    Koszt: {{ offer.cost }} zł dla jednej osoby.<br>
                    <a href="{% url 'main_system:remove_offer' offer.id %}">Usuń ofertę</a>
                {% else %}
                    <div class="card-title">
                        <h4>{{ offer }}</h4>
                    </div>
                    <div class="card-subtitle">
                        <h6 class="text-muted">{{ offer.other_provider.location }}</h6>
                    </div>
                    {% if offer.offer_description %}
                        {{ offer.offer_description }}<br>
                    {% endif %}
                    Numer telefonu: {{ offer.other_provider.contact.phone_number }}<br>
                    Koszt: {{ offer.cost }} zł.<br>
                    <a href="{% url 'main_system:remove_offer' offer.id %}">Usuń ofertę</a>
                {% endif %}
            </div>
        </div>
    {% empty %}
        Nie wybrałeś jeszcze żadnej z ofert.
    {% endfor %}

    <p>
        <a href="{% url 'main_system:estimate_costs' %}">Oszacuj koszty</a>
    </p>
{% endblock %}